### ISSUE TITLE
Exception when calling `catalog.getIndexDataForRID(rid)` 

### ISSUE THREAD

**Issue by petschki** [collective/Products.DateRangeInRangeIndex#11]
## Cause
Missing `getEntryForObject` method in the index object ...

## Solution
implement `getEntryForObject` which simply returns `None` as we're only a ProxyIndex

## Where does this happen?
The event_listing in Plone uses `catalog.getIndexDataForRID(rid)` to expand start/end dates for recurring events. If you have installed `Products.DateRangeInRangeIndex` you get an exception.

**Comment by icemac** [comment]
A traceback might be helpful to get a deeper knowledge about the issue.
