### ISSUE TITLE
The current master branch is not compatible with 2.13.26

### ISSUE THREAD

**Issue by sallner** [collective/Products.DateRangeInRangeIndex#2]
With the last commit, c18457681ae2972e819681d97bd7233dd6c163af, the `@security.protected` decorator was introduced which is not yet present in the pinned version for `AccessControl = 2.13.15`, which in turn is set by http://download.zope.org/Zope2/index/2.13.26/versions.cfg. 

I would like to have a version of this package, which does not depend on `Globals` anymore but does not need the full list of Zope 4 dependencies. 

It, therefore, seems reasonable to me to treat the current master as future 2.0 release and I would submit a PR to aim for a 1.4 release which does not depend on `Globals` anymore. 

@jensens Do you have any objections against this process?

**Comment by sallner** [comment]
@jensens It would be time for a 1.4.0 and a 2.0 release after these changes. Do you want to do that or add `icemac` and `sallner` on pypi to gain release permission?

**Comment by jensens** [comment]
Sorry for late reply, I am just back from holidays. +1 for all

Permissions granted!

**Comment by icemac** [comment]
Thanks @jensens.
